version: '3.8' 

services: 
  flask_app: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: flask_app 
    volumes: 
      - ./app:/app 
    ports: 
      - "5000:5000" 
    environment: 
      - FLASK_ENV=development